### ISSUE TITLE
A simple modification will improve the usefulness of this example.

### ISSUE THREAD

**Issue by BrienKing** [DevExpress-Examples/how-to-edit-multiple-values-in-gridview-at-the-same-time-e2779#1]
In the Method **SetSelectedCellValues**, there is this line:

````C#
view.SetRowCellValue(cell.RowHandle, cell.Column, value);
````

Which causes the value to be applied to ALL the columns in all the selected rows.  This is not a realistic example of what you want to do.

Instead, you should change the code to this:
````C#
view.SetRowCellValue(cell.RowHandle, view.FocusedColumn, value);
````
and it will only update the values in the column you are changing.

**Comment by AlexMedusa** [comment]
Hello Brien,

Thank you for the feedback. We will consider updating this example. Please let me know if I can be of more help.
